/* Main.c file generated by New Project wizard
 *
 * Created:   Tue Jan 8 2019
 * Processor: LPC2138
 * Compiler:  GCC for ARM
 */

#include <LPC213x.h>

int main (void)
 { 
   // Write your code here
   while (1)
      ;
   return 0;
 }   
